// Copyright (c) 2025 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// source: IAM/AsyncAPI/oauth.yaml (0.1.0)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: accelbyte-asyncapi/iam/oauth/v1/oauth.proto

package oauth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// path: #/components/schemas/event
type Event struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version         int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Namespace       string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ParentNamespace string                 `protobuf:"bytes,5,opt,name=parent_namespace,json=parentNamespace,proto3" json:"parent_namespace,omitempty"`
	Timestamp       string                 `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ClientId        string                 `protobuf:"bytes,7,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	UserId          string                 `protobuf:"bytes,8,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TraceId         string                 `protobuf:"bytes,9,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SessionId       string                 `protobuf:"bytes,10,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Event) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Event) GetParentNamespace() string {
	if x != nil {
		return x.ParentNamespace
	}
	return ""
}

func (x *Event) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Event) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Event) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Event) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Event) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// path: #/components/schemas/oauth
type Oauth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ResponseType  string                 `protobuf:"bytes,2,opt,name=response_type,json=responseType,proto3" json:"response_type,omitempty"`
	PlatformId    string                 `protobuf:"bytes,3,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Oauth) Reset() {
	*x = Oauth{}
	mi := &file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Oauth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Oauth) ProtoMessage() {}

func (x *Oauth) ProtoReflect() protoreflect.Message {
	mi := &file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Oauth.ProtoReflect.Descriptor instead.
func (*Oauth) Descriptor() ([]byte, []int) {
	return file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_rawDescGZIP(), []int{1}
}

func (x *Oauth) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Oauth) GetResponseType() string {
	if x != nil {
		return x.ResponseType
	}
	return ""
}

func (x *Oauth) GetPlatformId() string {
	if x != nil {
		return x.PlatformId
	}
	return ""
}

// path: #/components/schemas/oauthThirdParty
type OauthThirdParty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlatformId    string                 `protobuf:"bytes,1,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OauthThirdParty) Reset() {
	*x = OauthThirdParty{}
	mi := &file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OauthThirdParty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OauthThirdParty) ProtoMessage() {}

func (x *OauthThirdParty) ProtoReflect() protoreflect.Message {
	mi := &file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OauthThirdParty.ProtoReflect.Descriptor instead.
func (*OauthThirdParty) Descriptor() ([]byte, []int) {
	return file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_rawDescGZIP(), []int{2}
}

func (x *OauthThirdParty) GetPlatformId() string {
	if x != nil {
		return x.PlatformId
	}
	return ""
}

func (x *OauthThirdParty) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

// path: #/components/schemas/oauthRequestAuthorizedPayloadData
type OauthRequestAuthorizedPayloadData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Oauth         *Oauth                 `protobuf:"bytes,1,opt,name=oauth,proto3" json:"oauth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OauthRequestAuthorizedPayloadData) Reset() {
	*x = OauthRequestAuthorizedPayloadData{}
	mi := &file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OauthRequestAuthorizedPayloadData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OauthRequestAuthorizedPayloadData) ProtoMessage() {}

func (x *OauthRequestAuthorizedPayloadData) ProtoReflect() protoreflect.Message {
	mi := &file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OauthRequestAuthorizedPayloadData.ProtoReflect.Descriptor instead.
func (*OauthRequestAuthorizedPayloadData) Descriptor() ([]byte, []int) {
	return file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_rawDescGZIP(), []int{3}
}

func (x *OauthRequestAuthorizedPayloadData) GetOauth() *Oauth {
	if x != nil {
		return x.Oauth
	}
	return nil
}

// path: #/components/schemas/oauthTokenGeneratedPayloadData
type OauthTokenGeneratedPayloadData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Oauth         *Oauth                 `protobuf:"bytes,1,opt,name=oauth,proto3" json:"oauth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OauthTokenGeneratedPayloadData) Reset() {
	*x = OauthTokenGeneratedPayloadData{}
	mi := &file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OauthTokenGeneratedPayloadData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OauthTokenGeneratedPayloadData) ProtoMessage() {}

func (x *OauthTokenGeneratedPayloadData) ProtoReflect() protoreflect.Message {
	mi := &file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OauthTokenGeneratedPayloadData.ProtoReflect.Descriptor instead.
func (*OauthTokenGeneratedPayloadData) Descriptor() ([]byte, []int) {
	return file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_rawDescGZIP(), []int{4}
}

func (x *OauthTokenGeneratedPayloadData) GetOauth() *Oauth {
	if x != nil {
		return x.Oauth
	}
	return nil
}

// path: #/components/schemas/oauthTokenRevokedPayloadData
type OauthTokenRevokedPayloadData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Oauth         *Oauth                 `protobuf:"bytes,1,opt,name=oauth,proto3" json:"oauth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OauthTokenRevokedPayloadData) Reset() {
	*x = OauthTokenRevokedPayloadData{}
	mi := &file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OauthTokenRevokedPayloadData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OauthTokenRevokedPayloadData) ProtoMessage() {}

func (x *OauthTokenRevokedPayloadData) ProtoReflect() protoreflect.Message {
	mi := &file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OauthTokenRevokedPayloadData.ProtoReflect.Descriptor instead.
func (*OauthTokenRevokedPayloadData) Descriptor() ([]byte, []int) {
	return file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_rawDescGZIP(), []int{5}
}

func (x *OauthTokenRevokedPayloadData) GetOauth() *Oauth {
	if x != nil {
		return x.Oauth
	}
	return nil
}

// path: #/components/schemas/oauthThirdPartyRequestAuthorizedPayloadData
type OauthThirdPartyRequestAuthorizedPayloadData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Oauth           *Oauth                 `protobuf:"bytes,1,opt,name=oauth,proto3" json:"oauth,omitempty"`
	OauthThirdParty *OauthThirdParty       `protobuf:"bytes,2,opt,name=oauth_third_party,json=oauthThirdParty,proto3" json:"oauth_third_party,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OauthThirdPartyRequestAuthorizedPayloadData) Reset() {
	*x = OauthThirdPartyRequestAuthorizedPayloadData{}
	mi := &file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OauthThirdPartyRequestAuthorizedPayloadData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OauthThirdPartyRequestAuthorizedPayloadData) ProtoMessage() {}

func (x *OauthThirdPartyRequestAuthorizedPayloadData) ProtoReflect() protoreflect.Message {
	mi := &file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OauthThirdPartyRequestAuthorizedPayloadData.ProtoReflect.Descriptor instead.
func (*OauthThirdPartyRequestAuthorizedPayloadData) Descriptor() ([]byte, []int) {
	return file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_rawDescGZIP(), []int{6}
}

func (x *OauthThirdPartyRequestAuthorizedPayloadData) GetOauth() *Oauth {
	if x != nil {
		return x.Oauth
	}
	return nil
}

func (x *OauthThirdPartyRequestAuthorizedPayloadData) GetOauthThirdParty() *OauthThirdParty {
	if x != nil {
		return x.OauthThirdParty
	}
	return nil
}

// path: #/components/schemas/oauthThirdPartyTokenGeneratedPayloadData
type OauthThirdPartyTokenGeneratedPayloadData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Oauth           *Oauth                 `protobuf:"bytes,1,opt,name=oauth,proto3" json:"oauth,omitempty"`
	OauthThirdParty *OauthThirdParty       `protobuf:"bytes,2,opt,name=oauth_third_party,json=oauthThirdParty,proto3" json:"oauth_third_party,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OauthThirdPartyTokenGeneratedPayloadData) Reset() {
	*x = OauthThirdPartyTokenGeneratedPayloadData{}
	mi := &file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OauthThirdPartyTokenGeneratedPayloadData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OauthThirdPartyTokenGeneratedPayloadData) ProtoMessage() {}

func (x *OauthThirdPartyTokenGeneratedPayloadData) ProtoReflect() protoreflect.Message {
	mi := &file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OauthThirdPartyTokenGeneratedPayloadData.ProtoReflect.Descriptor instead.
func (*OauthThirdPartyTokenGeneratedPayloadData) Descriptor() ([]byte, []int) {
	return file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_rawDescGZIP(), []int{7}
}

func (x *OauthThirdPartyTokenGeneratedPayloadData) GetOauth() *Oauth {
	if x != nil {
		return x.Oauth
	}
	return nil
}

func (x *OauthThirdPartyTokenGeneratedPayloadData) GetOauthThirdParty() *OauthThirdParty {
	if x != nil {
		return x.OauthThirdParty
	}
	return nil
}

// path: #/components/messages/oauthRequestAuthorized/payload
type OauthRequestAuthorized struct {
	state   protoimpl.MessageState             `protogen:"open.v1"`
	Payload *OauthRequestAuthorizedPayloadData `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// allOf(#/components/schemas/event)
	Id              string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Version         int64  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Name            string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Namespace       string `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ParentNamespace string `protobuf:"bytes,6,opt,name=parent_namespace,json=parentNamespace,proto3" json:"parent_namespace,omitempty"`
	Timestamp       string `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ClientId        string `protobuf:"bytes,8,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	UserId          string `protobuf:"bytes,9,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TraceId         string `protobuf:"bytes,10,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SessionId       string `protobuf:"bytes,11,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OauthRequestAuthorized) Reset() {
	*x = OauthRequestAuthorized{}
	mi := &file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OauthRequestAuthorized) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OauthRequestAuthorized) ProtoMessage() {}

func (x *OauthRequestAuthorized) ProtoReflect() protoreflect.Message {
	mi := &file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OauthRequestAuthorized.ProtoReflect.Descriptor instead.
func (*OauthRequestAuthorized) Descriptor() ([]byte, []int) {
	return file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_rawDescGZIP(), []int{8}
}

func (x *OauthRequestAuthorized) GetPayload() *OauthRequestAuthorizedPayloadData {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *OauthRequestAuthorized) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OauthRequestAuthorized) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *OauthRequestAuthorized) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OauthRequestAuthorized) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *OauthRequestAuthorized) GetParentNamespace() string {
	if x != nil {
		return x.ParentNamespace
	}
	return ""
}

func (x *OauthRequestAuthorized) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *OauthRequestAuthorized) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *OauthRequestAuthorized) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OauthRequestAuthorized) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *OauthRequestAuthorized) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// path: #/components/messages/oauthTokenGenerated/payload
type OauthTokenGenerated struct {
	state   protoimpl.MessageState          `protogen:"open.v1"`
	Payload *OauthTokenGeneratedPayloadData `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// allOf(#/components/schemas/event)
	Id              string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Version         int64  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Name            string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Namespace       string `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ParentNamespace string `protobuf:"bytes,6,opt,name=parent_namespace,json=parentNamespace,proto3" json:"parent_namespace,omitempty"`
	Timestamp       string `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ClientId        string `protobuf:"bytes,8,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	UserId          string `protobuf:"bytes,9,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TraceId         string `protobuf:"bytes,10,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SessionId       string `protobuf:"bytes,11,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OauthTokenGenerated) Reset() {
	*x = OauthTokenGenerated{}
	mi := &file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OauthTokenGenerated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OauthTokenGenerated) ProtoMessage() {}

func (x *OauthTokenGenerated) ProtoReflect() protoreflect.Message {
	mi := &file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OauthTokenGenerated.ProtoReflect.Descriptor instead.
func (*OauthTokenGenerated) Descriptor() ([]byte, []int) {
	return file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_rawDescGZIP(), []int{9}
}

func (x *OauthTokenGenerated) GetPayload() *OauthTokenGeneratedPayloadData {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *OauthTokenGenerated) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OauthTokenGenerated) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *OauthTokenGenerated) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OauthTokenGenerated) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *OauthTokenGenerated) GetParentNamespace() string {
	if x != nil {
		return x.ParentNamespace
	}
	return ""
}

func (x *OauthTokenGenerated) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *OauthTokenGenerated) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *OauthTokenGenerated) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OauthTokenGenerated) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *OauthTokenGenerated) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// path: #/components/messages/oauthTokenRevoked/payload
type OauthTokenRevoked struct {
	state   protoimpl.MessageState        `protogen:"open.v1"`
	Payload *OauthTokenRevokedPayloadData `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// allOf(#/components/schemas/event)
	Id              string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Version         int64  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Name            string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Namespace       string `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ParentNamespace string `protobuf:"bytes,6,opt,name=parent_namespace,json=parentNamespace,proto3" json:"parent_namespace,omitempty"`
	Timestamp       string `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ClientId        string `protobuf:"bytes,8,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	UserId          string `protobuf:"bytes,9,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TraceId         string `protobuf:"bytes,10,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SessionId       string `protobuf:"bytes,11,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OauthTokenRevoked) Reset() {
	*x = OauthTokenRevoked{}
	mi := &file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OauthTokenRevoked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OauthTokenRevoked) ProtoMessage() {}

func (x *OauthTokenRevoked) ProtoReflect() protoreflect.Message {
	mi := &file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OauthTokenRevoked.ProtoReflect.Descriptor instead.
func (*OauthTokenRevoked) Descriptor() ([]byte, []int) {
	return file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_rawDescGZIP(), []int{10}
}

func (x *OauthTokenRevoked) GetPayload() *OauthTokenRevokedPayloadData {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *OauthTokenRevoked) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OauthTokenRevoked) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *OauthTokenRevoked) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OauthTokenRevoked) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *OauthTokenRevoked) GetParentNamespace() string {
	if x != nil {
		return x.ParentNamespace
	}
	return ""
}

func (x *OauthTokenRevoked) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *OauthTokenRevoked) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *OauthTokenRevoked) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OauthTokenRevoked) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *OauthTokenRevoked) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// path: #/components/messages/oauthThirdPartyRequestAuthorized/payload
type OauthThirdPartyRequestAuthorized struct {
	state   protoimpl.MessageState                       `protogen:"open.v1"`
	Payload *OauthThirdPartyRequestAuthorizedPayloadData `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// allOf(#/components/schemas/event)
	Id              string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Version         int64  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Name            string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Namespace       string `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ParentNamespace string `protobuf:"bytes,6,opt,name=parent_namespace,json=parentNamespace,proto3" json:"parent_namespace,omitempty"`
	Timestamp       string `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ClientId        string `protobuf:"bytes,8,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	UserId          string `protobuf:"bytes,9,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TraceId         string `protobuf:"bytes,10,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SessionId       string `protobuf:"bytes,11,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OauthThirdPartyRequestAuthorized) Reset() {
	*x = OauthThirdPartyRequestAuthorized{}
	mi := &file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OauthThirdPartyRequestAuthorized) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OauthThirdPartyRequestAuthorized) ProtoMessage() {}

func (x *OauthThirdPartyRequestAuthorized) ProtoReflect() protoreflect.Message {
	mi := &file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OauthThirdPartyRequestAuthorized.ProtoReflect.Descriptor instead.
func (*OauthThirdPartyRequestAuthorized) Descriptor() ([]byte, []int) {
	return file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_rawDescGZIP(), []int{11}
}

func (x *OauthThirdPartyRequestAuthorized) GetPayload() *OauthThirdPartyRequestAuthorizedPayloadData {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *OauthThirdPartyRequestAuthorized) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OauthThirdPartyRequestAuthorized) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *OauthThirdPartyRequestAuthorized) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OauthThirdPartyRequestAuthorized) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *OauthThirdPartyRequestAuthorized) GetParentNamespace() string {
	if x != nil {
		return x.ParentNamespace
	}
	return ""
}

func (x *OauthThirdPartyRequestAuthorized) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *OauthThirdPartyRequestAuthorized) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *OauthThirdPartyRequestAuthorized) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OauthThirdPartyRequestAuthorized) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *OauthThirdPartyRequestAuthorized) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// path: #/components/messages/oauthThirdPartyTokenGenerated/payload
type OauthThirdPartyTokenGenerated struct {
	state   protoimpl.MessageState                    `protogen:"open.v1"`
	Payload *OauthThirdPartyTokenGeneratedPayloadData `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// allOf(#/components/schemas/event)
	Id              string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Version         int64  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Name            string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Namespace       string `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ParentNamespace string `protobuf:"bytes,6,opt,name=parent_namespace,json=parentNamespace,proto3" json:"parent_namespace,omitempty"`
	Timestamp       string `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ClientId        string `protobuf:"bytes,8,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	UserId          string `protobuf:"bytes,9,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TraceId         string `protobuf:"bytes,10,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SessionId       string `protobuf:"bytes,11,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OauthThirdPartyTokenGenerated) Reset() {
	*x = OauthThirdPartyTokenGenerated{}
	mi := &file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OauthThirdPartyTokenGenerated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OauthThirdPartyTokenGenerated) ProtoMessage() {}

func (x *OauthThirdPartyTokenGenerated) ProtoReflect() protoreflect.Message {
	mi := &file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OauthThirdPartyTokenGenerated.ProtoReflect.Descriptor instead.
func (*OauthThirdPartyTokenGenerated) Descriptor() ([]byte, []int) {
	return file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_rawDescGZIP(), []int{12}
}

func (x *OauthThirdPartyTokenGenerated) GetPayload() *OauthThirdPartyTokenGeneratedPayloadData {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *OauthThirdPartyTokenGenerated) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OauthThirdPartyTokenGenerated) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *OauthThirdPartyTokenGenerated) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OauthThirdPartyTokenGenerated) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *OauthThirdPartyTokenGenerated) GetParentNamespace() string {
	if x != nil {
		return x.ParentNamespace
	}
	return ""
}

func (x *OauthThirdPartyTokenGenerated) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *OauthThirdPartyTokenGenerated) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *OauthThirdPartyTokenGenerated) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OauthThirdPartyTokenGenerated) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *OauthThirdPartyTokenGenerated) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// path: #/components/messages/oauthRequestAuthorized
type OauthRequestAuthorizedMessage struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Payload       *OauthRequestAuthorized `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OauthRequestAuthorizedMessage) Reset() {
	*x = OauthRequestAuthorizedMessage{}
	mi := &file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OauthRequestAuthorizedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OauthRequestAuthorizedMessage) ProtoMessage() {}

func (x *OauthRequestAuthorizedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OauthRequestAuthorizedMessage.ProtoReflect.Descriptor instead.
func (*OauthRequestAuthorizedMessage) Descriptor() ([]byte, []int) {
	return file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_rawDescGZIP(), []int{13}
}

func (x *OauthRequestAuthorizedMessage) GetPayload() *OauthRequestAuthorized {
	if x != nil {
		return x.Payload
	}
	return nil
}

// path: #/components/messages/oauthTokenGenerated
type OauthTokenGeneratedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *OauthTokenGenerated   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OauthTokenGeneratedMessage) Reset() {
	*x = OauthTokenGeneratedMessage{}
	mi := &file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OauthTokenGeneratedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OauthTokenGeneratedMessage) ProtoMessage() {}

func (x *OauthTokenGeneratedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OauthTokenGeneratedMessage.ProtoReflect.Descriptor instead.
func (*OauthTokenGeneratedMessage) Descriptor() ([]byte, []int) {
	return file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_rawDescGZIP(), []int{14}
}

func (x *OauthTokenGeneratedMessage) GetPayload() *OauthTokenGenerated {
	if x != nil {
		return x.Payload
	}
	return nil
}

// path: #/components/messages/oauthTokenRevoked
type OauthTokenRevokedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *OauthTokenRevoked     `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OauthTokenRevokedMessage) Reset() {
	*x = OauthTokenRevokedMessage{}
	mi := &file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OauthTokenRevokedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OauthTokenRevokedMessage) ProtoMessage() {}

func (x *OauthTokenRevokedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OauthTokenRevokedMessage.ProtoReflect.Descriptor instead.
func (*OauthTokenRevokedMessage) Descriptor() ([]byte, []int) {
	return file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_rawDescGZIP(), []int{15}
}

func (x *OauthTokenRevokedMessage) GetPayload() *OauthTokenRevoked {
	if x != nil {
		return x.Payload
	}
	return nil
}

// path: #/components/messages/oauthThirdPartyRequestAuthorized
type OauthThirdPartyRequestAuthorizedMessage struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Payload       *OauthThirdPartyRequestAuthorized `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OauthThirdPartyRequestAuthorizedMessage) Reset() {
	*x = OauthThirdPartyRequestAuthorizedMessage{}
	mi := &file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OauthThirdPartyRequestAuthorizedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OauthThirdPartyRequestAuthorizedMessage) ProtoMessage() {}

func (x *OauthThirdPartyRequestAuthorizedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OauthThirdPartyRequestAuthorizedMessage.ProtoReflect.Descriptor instead.
func (*OauthThirdPartyRequestAuthorizedMessage) Descriptor() ([]byte, []int) {
	return file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_rawDescGZIP(), []int{16}
}

func (x *OauthThirdPartyRequestAuthorizedMessage) GetPayload() *OauthThirdPartyRequestAuthorized {
	if x != nil {
		return x.Payload
	}
	return nil
}

// path: #/components/messages/oauthThirdPartyTokenGenerated
type OauthThirdPartyTokenGeneratedMessage struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Payload       *OauthThirdPartyTokenGenerated `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OauthThirdPartyTokenGeneratedMessage) Reset() {
	*x = OauthThirdPartyTokenGeneratedMessage{}
	mi := &file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OauthThirdPartyTokenGeneratedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OauthThirdPartyTokenGeneratedMessage) ProtoMessage() {}

func (x *OauthThirdPartyTokenGeneratedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OauthThirdPartyTokenGeneratedMessage.ProtoReflect.Descriptor instead.
func (*OauthThirdPartyTokenGeneratedMessage) Descriptor() ([]byte, []int) {
	return file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_rawDescGZIP(), []int{17}
}

func (x *OauthThirdPartyTokenGeneratedMessage) GetPayload() *OauthThirdPartyTokenGenerated {
	if x != nil {
		return x.Payload
	}
	return nil
}

// path: #/channels/oauthToken/publish/message
type OauthTokenPublish struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*OauthTokenPublish_Variant0
	//	*OauthTokenPublish_Variant1
	Payload       isOauthTokenPublish_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OauthTokenPublish) Reset() {
	*x = OauthTokenPublish{}
	mi := &file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OauthTokenPublish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OauthTokenPublish) ProtoMessage() {}

func (x *OauthTokenPublish) ProtoReflect() protoreflect.Message {
	mi := &file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OauthTokenPublish.ProtoReflect.Descriptor instead.
func (*OauthTokenPublish) Descriptor() ([]byte, []int) {
	return file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_rawDescGZIP(), []int{18}
}

func (x *OauthTokenPublish) GetPayload() isOauthTokenPublish_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *OauthTokenPublish) GetVariant0() *OauthTokenGeneratedMessage {
	if x != nil {
		if x, ok := x.Payload.(*OauthTokenPublish_Variant0); ok {
			return x.Variant0
		}
	}
	return nil
}

func (x *OauthTokenPublish) GetVariant1() *OauthTokenRevokedMessage {
	if x != nil {
		if x, ok := x.Payload.(*OauthTokenPublish_Variant1); ok {
			return x.Variant1
		}
	}
	return nil
}

type isOauthTokenPublish_Payload interface {
	isOauthTokenPublish_Payload()
}

type OauthTokenPublish_Variant0 struct {
	Variant0 *OauthTokenGeneratedMessage `protobuf:"bytes,1,opt,name=variant0,proto3,oneof"`
}

type OauthTokenPublish_Variant1 struct {
	Variant1 *OauthTokenRevokedMessage `protobuf:"bytes,2,opt,name=variant1,proto3,oneof"`
}

func (*OauthTokenPublish_Variant0) isOauthTokenPublish_Payload() {}

func (*OauthTokenPublish_Variant1) isOauthTokenPublish_Payload() {}

var File_accelbyte_asyncapi_iam_oauth_v1_oauth_proto protoreflect.FileDescriptor

const file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_rawDesc = "" +
	"\n" +
	"+accelbyte-asyncapi/iam/oauth/v1/oauth.proto\x12\x16accelbyte.iam.oauth.v1\x1a\x19google/protobuf/any.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x9c\x02\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12)\n" +
	"\x10parent_namespace\x18\x05 \x01(\tR\x0fparentNamespace\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\tR\ttimestamp\x12\x1b\n" +
	"\tclient_id\x18\a \x01(\tR\bclientId\x12\x17\n" +
	"\auser_id\x18\b \x01(\tR\x06userId\x12\x19\n" +
	"\btrace_id\x18\t \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"session_id\x18\n" +
	" \x01(\tR\tsessionId\"j\n" +
	"\x05Oauth\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12#\n" +
	"\rresponse_type\x18\x02 \x01(\tR\fresponseType\x12\x1f\n" +
	"\vplatform_id\x18\x03 \x01(\tR\n" +
	"platformId\"U\n" +
	"\x0fOauthThirdParty\x12\x1f\n" +
	"\vplatform_id\x18\x01 \x01(\tR\n" +
	"platformId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\"X\n" +
	"!OauthRequestAuthorizedPayloadData\x123\n" +
	"\x05oauth\x18\x01 \x01(\v2\x1d.accelbyte.iam.oauth.v1.OauthR\x05oauth\"U\n" +
	"\x1eOauthTokenGeneratedPayloadData\x123\n" +
	"\x05oauth\x18\x01 \x01(\v2\x1d.accelbyte.iam.oauth.v1.OauthR\x05oauth\"S\n" +
	"\x1cOauthTokenRevokedPayloadData\x123\n" +
	"\x05oauth\x18\x01 \x01(\v2\x1d.accelbyte.iam.oauth.v1.OauthR\x05oauth\"\xb7\x01\n" +
	"+OauthThirdPartyRequestAuthorizedPayloadData\x123\n" +
	"\x05oauth\x18\x01 \x01(\v2\x1d.accelbyte.iam.oauth.v1.OauthR\x05oauth\x12S\n" +
	"\x11oauth_third_party\x18\x02 \x01(\v2'.accelbyte.iam.oauth.v1.OauthThirdPartyR\x0foauthThirdParty\"\xb4\x01\n" +
	"(OauthThirdPartyTokenGeneratedPayloadData\x123\n" +
	"\x05oauth\x18\x01 \x01(\v2\x1d.accelbyte.iam.oauth.v1.OauthR\x05oauth\x12S\n" +
	"\x11oauth_third_party\x18\x02 \x01(\v2'.accelbyte.iam.oauth.v1.OauthThirdPartyR\x0foauthThirdParty\"\x82\x03\n" +
	"\x16OauthRequestAuthorized\x12S\n" +
	"\apayload\x18\x01 \x01(\v29.accelbyte.iam.oauth.v1.OauthRequestAuthorizedPayloadDataR\apayload\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12)\n" +
	"\x10parent_namespace\x18\x06 \x01(\tR\x0fparentNamespace\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\tR\ttimestamp\x12\x1b\n" +
	"\tclient_id\x18\b \x01(\tR\bclientId\x12\x17\n" +
	"\auser_id\x18\t \x01(\tR\x06userId\x12\x19\n" +
	"\btrace_id\x18\n" +
	" \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"session_id\x18\v \x01(\tR\tsessionId\"\xfc\x02\n" +
	"\x13OauthTokenGenerated\x12P\n" +
	"\apayload\x18\x01 \x01(\v26.accelbyte.iam.oauth.v1.OauthTokenGeneratedPayloadDataR\apayload\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12)\n" +
	"\x10parent_namespace\x18\x06 \x01(\tR\x0fparentNamespace\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\tR\ttimestamp\x12\x1b\n" +
	"\tclient_id\x18\b \x01(\tR\bclientId\x12\x17\n" +
	"\auser_id\x18\t \x01(\tR\x06userId\x12\x19\n" +
	"\btrace_id\x18\n" +
	" \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"session_id\x18\v \x01(\tR\tsessionId\"\xf8\x02\n" +
	"\x11OauthTokenRevoked\x12N\n" +
	"\apayload\x18\x01 \x01(\v24.accelbyte.iam.oauth.v1.OauthTokenRevokedPayloadDataR\apayload\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12)\n" +
	"\x10parent_namespace\x18\x06 \x01(\tR\x0fparentNamespace\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\tR\ttimestamp\x12\x1b\n" +
	"\tclient_id\x18\b \x01(\tR\bclientId\x12\x17\n" +
	"\auser_id\x18\t \x01(\tR\x06userId\x12\x19\n" +
	"\btrace_id\x18\n" +
	" \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"session_id\x18\v \x01(\tR\tsessionId\"\x96\x03\n" +
	" OauthThirdPartyRequestAuthorized\x12]\n" +
	"\apayload\x18\x01 \x01(\v2C.accelbyte.iam.oauth.v1.OauthThirdPartyRequestAuthorizedPayloadDataR\apayload\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12)\n" +
	"\x10parent_namespace\x18\x06 \x01(\tR\x0fparentNamespace\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\tR\ttimestamp\x12\x1b\n" +
	"\tclient_id\x18\b \x01(\tR\bclientId\x12\x17\n" +
	"\auser_id\x18\t \x01(\tR\x06userId\x12\x19\n" +
	"\btrace_id\x18\n" +
	" \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"session_id\x18\v \x01(\tR\tsessionId\"\x90\x03\n" +
	"\x1dOauthThirdPartyTokenGenerated\x12Z\n" +
	"\apayload\x18\x01 \x01(\v2@.accelbyte.iam.oauth.v1.OauthThirdPartyTokenGeneratedPayloadDataR\apayload\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12)\n" +
	"\x10parent_namespace\x18\x06 \x01(\tR\x0fparentNamespace\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\tR\ttimestamp\x12\x1b\n" +
	"\tclient_id\x18\b \x01(\tR\bclientId\x12\x17\n" +
	"\auser_id\x18\t \x01(\tR\x06userId\x12\x19\n" +
	"\btrace_id\x18\n" +
	" \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"session_id\x18\v \x01(\tR\tsessionId\"i\n" +
	"\x1dOauthRequestAuthorizedMessage\x12H\n" +
	"\apayload\x18\x01 \x01(\v2..accelbyte.iam.oauth.v1.OauthRequestAuthorizedR\apayload\"c\n" +
	"\x1aOauthTokenGeneratedMessage\x12E\n" +
	"\apayload\x18\x01 \x01(\v2+.accelbyte.iam.oauth.v1.OauthTokenGeneratedR\apayload\"_\n" +
	"\x18OauthTokenRevokedMessage\x12C\n" +
	"\apayload\x18\x01 \x01(\v2).accelbyte.iam.oauth.v1.OauthTokenRevokedR\apayload\"}\n" +
	"'OauthThirdPartyRequestAuthorizedMessage\x12R\n" +
	"\apayload\x18\x01 \x01(\v28.accelbyte.iam.oauth.v1.OauthThirdPartyRequestAuthorizedR\apayload\"w\n" +
	"$OauthThirdPartyTokenGeneratedMessage\x12O\n" +
	"\apayload\x18\x01 \x01(\v25.accelbyte.iam.oauth.v1.OauthThirdPartyTokenGeneratedR\apayload\"\xc0\x01\n" +
	"\x11OauthTokenPublish\x12P\n" +
	"\bvariant0\x18\x01 \x01(\v22.accelbyte.iam.oauth.v1.OauthTokenGeneratedMessageH\x00R\bvariant0\x12N\n" +
	"\bvariant1\x18\x02 \x01(\v20.accelbyte.iam.oauth.v1.OauthTokenRevokedMessageH\x00R\bvariant1B\t\n" +
	"\apayload2\x80\x01\n" +
	")OauthRequestOauthRequestAuthorizedService\x12S\n" +
	"\tOnMessage\x12..accelbyte.iam.oauth.v1.OauthRequestAuthorized\x1a\x16.google.protobuf.Empty2x\n" +
	"$OauthTokenOauthTokenGeneratedService\x12P\n" +
	"\tOnMessage\x12+.accelbyte.iam.oauth.v1.OauthTokenGenerated\x1a\x16.google.protobuf.Empty2t\n" +
	"\"OauthTokenOauthTokenRevokedService\x12N\n" +
	"\tOnMessage\x12).accelbyte.iam.oauth.v1.OauthTokenRevoked\x1a\x16.google.protobuf.Empty2\x9e\x01\n" +
	"=OauthThirdPartyRequestOauthThirdPartyRequestAuthorizedService\x12]\n" +
	"\tOnMessage\x128.accelbyte.iam.oauth.v1.OauthThirdPartyRequestAuthorized\x1a\x16.google.protobuf.Empty2\x96\x01\n" +
	"8OauthThirdPartyTokenOauthThirdPartyTokenGeneratedService\x12Z\n" +
	"\tOnMessage\x125.accelbyte.iam.oauth.v1.OauthThirdPartyTokenGenerated\x1a\x16.google.protobuf.EmptyBJ\n" +
	"\x17net.accelbyte.iam.oauthP\x01Z\x17accelbyte.net/iam/oauth\xaa\x02\x13AccelByte.IAM.Oauthb\x06proto3"

var (
	file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_rawDescOnce sync.Once
	file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_rawDescData []byte
)

func file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_rawDescGZIP() []byte {
	file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_rawDescOnce.Do(func() {
		file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_rawDesc), len(file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_rawDesc)))
	})
	return file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_rawDescData
}

var file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_goTypes = []any{
	(*Event)(nil),           // 0: accelbyte.iam.oauth.v1.Event
	(*Oauth)(nil),           // 1: accelbyte.iam.oauth.v1.Oauth
	(*OauthThirdParty)(nil), // 2: accelbyte.iam.oauth.v1.OauthThirdParty
	(*OauthRequestAuthorizedPayloadData)(nil),           // 3: accelbyte.iam.oauth.v1.OauthRequestAuthorizedPayloadData
	(*OauthTokenGeneratedPayloadData)(nil),              // 4: accelbyte.iam.oauth.v1.OauthTokenGeneratedPayloadData
	(*OauthTokenRevokedPayloadData)(nil),                // 5: accelbyte.iam.oauth.v1.OauthTokenRevokedPayloadData
	(*OauthThirdPartyRequestAuthorizedPayloadData)(nil), // 6: accelbyte.iam.oauth.v1.OauthThirdPartyRequestAuthorizedPayloadData
	(*OauthThirdPartyTokenGeneratedPayloadData)(nil),    // 7: accelbyte.iam.oauth.v1.OauthThirdPartyTokenGeneratedPayloadData
	(*OauthRequestAuthorized)(nil),                      // 8: accelbyte.iam.oauth.v1.OauthRequestAuthorized
	(*OauthTokenGenerated)(nil),                         // 9: accelbyte.iam.oauth.v1.OauthTokenGenerated
	(*OauthTokenRevoked)(nil),                           // 10: accelbyte.iam.oauth.v1.OauthTokenRevoked
	(*OauthThirdPartyRequestAuthorized)(nil),            // 11: accelbyte.iam.oauth.v1.OauthThirdPartyRequestAuthorized
	(*OauthThirdPartyTokenGenerated)(nil),               // 12: accelbyte.iam.oauth.v1.OauthThirdPartyTokenGenerated
	(*OauthRequestAuthorizedMessage)(nil),               // 13: accelbyte.iam.oauth.v1.OauthRequestAuthorizedMessage
	(*OauthTokenGeneratedMessage)(nil),                  // 14: accelbyte.iam.oauth.v1.OauthTokenGeneratedMessage
	(*OauthTokenRevokedMessage)(nil),                    // 15: accelbyte.iam.oauth.v1.OauthTokenRevokedMessage
	(*OauthThirdPartyRequestAuthorizedMessage)(nil),     // 16: accelbyte.iam.oauth.v1.OauthThirdPartyRequestAuthorizedMessage
	(*OauthThirdPartyTokenGeneratedMessage)(nil),        // 17: accelbyte.iam.oauth.v1.OauthThirdPartyTokenGeneratedMessage
	(*OauthTokenPublish)(nil),                           // 18: accelbyte.iam.oauth.v1.OauthTokenPublish
	(*emptypb.Empty)(nil),                               // 19: google.protobuf.Empty
}
var file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_depIdxs = []int32{
	1,  // 0: accelbyte.iam.oauth.v1.OauthRequestAuthorizedPayloadData.oauth:type_name -> accelbyte.iam.oauth.v1.Oauth
	1,  // 1: accelbyte.iam.oauth.v1.OauthTokenGeneratedPayloadData.oauth:type_name -> accelbyte.iam.oauth.v1.Oauth
	1,  // 2: accelbyte.iam.oauth.v1.OauthTokenRevokedPayloadData.oauth:type_name -> accelbyte.iam.oauth.v1.Oauth
	1,  // 3: accelbyte.iam.oauth.v1.OauthThirdPartyRequestAuthorizedPayloadData.oauth:type_name -> accelbyte.iam.oauth.v1.Oauth
	2,  // 4: accelbyte.iam.oauth.v1.OauthThirdPartyRequestAuthorizedPayloadData.oauth_third_party:type_name -> accelbyte.iam.oauth.v1.OauthThirdParty
	1,  // 5: accelbyte.iam.oauth.v1.OauthThirdPartyTokenGeneratedPayloadData.oauth:type_name -> accelbyte.iam.oauth.v1.Oauth
	2,  // 6: accelbyte.iam.oauth.v1.OauthThirdPartyTokenGeneratedPayloadData.oauth_third_party:type_name -> accelbyte.iam.oauth.v1.OauthThirdParty
	3,  // 7: accelbyte.iam.oauth.v1.OauthRequestAuthorized.payload:type_name -> accelbyte.iam.oauth.v1.OauthRequestAuthorizedPayloadData
	4,  // 8: accelbyte.iam.oauth.v1.OauthTokenGenerated.payload:type_name -> accelbyte.iam.oauth.v1.OauthTokenGeneratedPayloadData
	5,  // 9: accelbyte.iam.oauth.v1.OauthTokenRevoked.payload:type_name -> accelbyte.iam.oauth.v1.OauthTokenRevokedPayloadData
	6,  // 10: accelbyte.iam.oauth.v1.OauthThirdPartyRequestAuthorized.payload:type_name -> accelbyte.iam.oauth.v1.OauthThirdPartyRequestAuthorizedPayloadData
	7,  // 11: accelbyte.iam.oauth.v1.OauthThirdPartyTokenGenerated.payload:type_name -> accelbyte.iam.oauth.v1.OauthThirdPartyTokenGeneratedPayloadData
	8,  // 12: accelbyte.iam.oauth.v1.OauthRequestAuthorizedMessage.payload:type_name -> accelbyte.iam.oauth.v1.OauthRequestAuthorized
	9,  // 13: accelbyte.iam.oauth.v1.OauthTokenGeneratedMessage.payload:type_name -> accelbyte.iam.oauth.v1.OauthTokenGenerated
	10, // 14: accelbyte.iam.oauth.v1.OauthTokenRevokedMessage.payload:type_name -> accelbyte.iam.oauth.v1.OauthTokenRevoked
	11, // 15: accelbyte.iam.oauth.v1.OauthThirdPartyRequestAuthorizedMessage.payload:type_name -> accelbyte.iam.oauth.v1.OauthThirdPartyRequestAuthorized
	12, // 16: accelbyte.iam.oauth.v1.OauthThirdPartyTokenGeneratedMessage.payload:type_name -> accelbyte.iam.oauth.v1.OauthThirdPartyTokenGenerated
	14, // 17: accelbyte.iam.oauth.v1.OauthTokenPublish.variant0:type_name -> accelbyte.iam.oauth.v1.OauthTokenGeneratedMessage
	15, // 18: accelbyte.iam.oauth.v1.OauthTokenPublish.variant1:type_name -> accelbyte.iam.oauth.v1.OauthTokenRevokedMessage
	8,  // 19: accelbyte.iam.oauth.v1.OauthRequestOauthRequestAuthorizedService.OnMessage:input_type -> accelbyte.iam.oauth.v1.OauthRequestAuthorized
	9,  // 20: accelbyte.iam.oauth.v1.OauthTokenOauthTokenGeneratedService.OnMessage:input_type -> accelbyte.iam.oauth.v1.OauthTokenGenerated
	10, // 21: accelbyte.iam.oauth.v1.OauthTokenOauthTokenRevokedService.OnMessage:input_type -> accelbyte.iam.oauth.v1.OauthTokenRevoked
	11, // 22: accelbyte.iam.oauth.v1.OauthThirdPartyRequestOauthThirdPartyRequestAuthorizedService.OnMessage:input_type -> accelbyte.iam.oauth.v1.OauthThirdPartyRequestAuthorized
	12, // 23: accelbyte.iam.oauth.v1.OauthThirdPartyTokenOauthThirdPartyTokenGeneratedService.OnMessage:input_type -> accelbyte.iam.oauth.v1.OauthThirdPartyTokenGenerated
	19, // 24: accelbyte.iam.oauth.v1.OauthRequestOauthRequestAuthorizedService.OnMessage:output_type -> google.protobuf.Empty
	19, // 25: accelbyte.iam.oauth.v1.OauthTokenOauthTokenGeneratedService.OnMessage:output_type -> google.protobuf.Empty
	19, // 26: accelbyte.iam.oauth.v1.OauthTokenOauthTokenRevokedService.OnMessage:output_type -> google.protobuf.Empty
	19, // 27: accelbyte.iam.oauth.v1.OauthThirdPartyRequestOauthThirdPartyRequestAuthorizedService.OnMessage:output_type -> google.protobuf.Empty
	19, // 28: accelbyte.iam.oauth.v1.OauthThirdPartyTokenOauthThirdPartyTokenGeneratedService.OnMessage:output_type -> google.protobuf.Empty
	24, // [24:29] is the sub-list for method output_type
	19, // [19:24] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_init() }
func file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_init() {
	if File_accelbyte_asyncapi_iam_oauth_v1_oauth_proto != nil {
		return
	}
	file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_msgTypes[18].OneofWrappers = []any{
		(*OauthTokenPublish_Variant0)(nil),
		(*OauthTokenPublish_Variant1)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_rawDesc), len(file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_goTypes,
		DependencyIndexes: file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_depIdxs,
		MessageInfos:      file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_msgTypes,
	}.Build()
	File_accelbyte_asyncapi_iam_oauth_v1_oauth_proto = out.File
	file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_goTypes = nil
	file_accelbyte_asyncapi_iam_oauth_v1_oauth_proto_depIdxs = nil
}
