// Copyright (c) 2023 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.31.1
// source: service.proto

package serviceextension

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Service_CreateUserBehaviorTelemetry_FullMethodName = "/service.Service/CreateUserBehaviorTelemetry"
	Service_CreateGameplayTelemetry_FullMethodName     = "/service.Service/CreateGameplayTelemetry"
	Service_CreatePerformanceTelemetry_FullMethodName  = "/service.Service/CreatePerformanceTelemetry"
)

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	CreateUserBehaviorTelemetry(ctx context.Context, in *CreateUserBehaviorTelemetryRequest, opts ...grpc.CallOption) (*CreateTelemetryResponse, error)
	CreateGameplayTelemetry(ctx context.Context, in *CreateGameplayTelemetryRequest, opts ...grpc.CallOption) (*CreateTelemetryResponse, error)
	CreatePerformanceTelemetry(ctx context.Context, in *CreatePerformanceTelemetryRequest, opts ...grpc.CallOption) (*CreateTelemetryResponse, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) CreateUserBehaviorTelemetry(ctx context.Context, in *CreateUserBehaviorTelemetryRequest, opts ...grpc.CallOption) (*CreateTelemetryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTelemetryResponse)
	err := c.cc.Invoke(ctx, Service_CreateUserBehaviorTelemetry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) CreateGameplayTelemetry(ctx context.Context, in *CreateGameplayTelemetryRequest, opts ...grpc.CallOption) (*CreateTelemetryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTelemetryResponse)
	err := c.cc.Invoke(ctx, Service_CreateGameplayTelemetry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) CreatePerformanceTelemetry(ctx context.Context, in *CreatePerformanceTelemetryRequest, opts ...grpc.CallOption) (*CreateTelemetryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTelemetryResponse)
	err := c.cc.Invoke(ctx, Service_CreatePerformanceTelemetry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
// All implementations should embed UnimplementedServiceServer
// for forward compatibility.
type ServiceServer interface {
	CreateUserBehaviorTelemetry(context.Context, *CreateUserBehaviorTelemetryRequest) (*CreateTelemetryResponse, error)
	CreateGameplayTelemetry(context.Context, *CreateGameplayTelemetryRequest) (*CreateTelemetryResponse, error)
	CreatePerformanceTelemetry(context.Context, *CreatePerformanceTelemetryRequest) (*CreateTelemetryResponse, error)
}

// UnimplementedServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceServer struct{}

func (UnimplementedServiceServer) CreateUserBehaviorTelemetry(context.Context, *CreateUserBehaviorTelemetryRequest) (*CreateTelemetryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUserBehaviorTelemetry not implemented")
}
func (UnimplementedServiceServer) CreateGameplayTelemetry(context.Context, *CreateGameplayTelemetryRequest) (*CreateTelemetryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGameplayTelemetry not implemented")
}
func (UnimplementedServiceServer) CreatePerformanceTelemetry(context.Context, *CreatePerformanceTelemetryRequest) (*CreateTelemetryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePerformanceTelemetry not implemented")
}
func (UnimplementedServiceServer) testEmbeddedByValue() {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	// If the following call panics, it indicates UnimplementedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_CreateUserBehaviorTelemetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserBehaviorTelemetryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).CreateUserBehaviorTelemetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_CreateUserBehaviorTelemetry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).CreateUserBehaviorTelemetry(ctx, req.(*CreateUserBehaviorTelemetryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_CreateGameplayTelemetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGameplayTelemetryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).CreateGameplayTelemetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_CreateGameplayTelemetry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).CreateGameplayTelemetry(ctx, req.(*CreateGameplayTelemetryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_CreatePerformanceTelemetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePerformanceTelemetryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).CreatePerformanceTelemetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_CreatePerformanceTelemetry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).CreatePerformanceTelemetry(ctx, req.(*CreatePerformanceTelemetryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUserBehaviorTelemetry",
			Handler:    _Service_CreateUserBehaviorTelemetry_Handler,
		},
		{
			MethodName: "CreateGameplayTelemetry",
			Handler:    _Service_CreateGameplayTelemetry_Handler,
		},
		{
			MethodName: "CreatePerformanceTelemetry",
			Handler:    _Service_CreatePerformanceTelemetry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
