// Copyright (c) 2023 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: service.proto

package serviceextension

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Shared response for all telemetry endpoints
type CreateTelemetryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTelemetryResponse) Reset() {
	*x = CreateTelemetryResponse{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTelemetryResponse) ProtoMessage() {}

func (x *CreateTelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTelemetryResponse.ProtoReflect.Descriptor instead.
func (*CreateTelemetryResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

type UserInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Country           string                 `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	Platform          string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	AcquisitionSource string                 `protobuf:"bytes,4,opt,name=acquisition_source,json=acquisitionSource,proto3" json:"acquisition_source,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *UserInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserInfo) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *UserInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *UserInfo) GetAcquisitionSource() string {
	if x != nil {
		return x.AcquisitionSource
	}
	return ""
}

type UserBehaviorContext struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SessionId          string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TotalPlaytimeHours float64                `protobuf:"fixed64,2,opt,name=total_playtime_hours,json=totalPlaytimeHours,proto3" json:"total_playtime_hours,omitempty"`
	LastLogin          string                 `protobuf:"bytes,3,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UserBehaviorContext) Reset() {
	*x = UserBehaviorContext{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBehaviorContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBehaviorContext) ProtoMessage() {}

func (x *UserBehaviorContext) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBehaviorContext.ProtoReflect.Descriptor instead.
func (*UserBehaviorContext) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *UserBehaviorContext) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UserBehaviorContext) GetTotalPlaytimeHours() float64 {
	if x != nil {
		return x.TotalPlaytimeHours
	}
	return 0
}

func (x *UserBehaviorContext) GetLastLogin() string {
	if x != nil {
		return x.LastLogin
	}
	return ""
}

type CreateUserBehaviorTelemetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	User          *UserInfo              `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	Context       *UserBehaviorContext   `protobuf:"bytes,5,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserBehaviorTelemetryRequest) Reset() {
	*x = CreateUserBehaviorTelemetryRequest{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserBehaviorTelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserBehaviorTelemetryRequest) ProtoMessage() {}

func (x *CreateUserBehaviorTelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserBehaviorTelemetryRequest.ProtoReflect.Descriptor instead.
func (*CreateUserBehaviorTelemetryRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateUserBehaviorTelemetryRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CreateUserBehaviorTelemetryRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CreateUserBehaviorTelemetryRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *CreateUserBehaviorTelemetryRequest) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *CreateUserBehaviorTelemetryRequest) GetContext() *UserBehaviorContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float64                `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *Location) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Location) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Location) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

type GameplayData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Location       *Location              `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	MapId          string                 `protobuf:"bytes,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	Cause          string                 `protobuf:"bytes,3,opt,name=cause,proto3" json:"cause,omitempty"`
	ActiveWeapon   string                 `protobuf:"bytes,4,opt,name=active_weapon,json=activeWeapon,proto3" json:"active_weapon,omitempty"`
	AttackerId     string                 `protobuf:"bytes,5,opt,name=attacker_id,json=attackerId,proto3" json:"attacker_id,omitempty"`
	CurrentMission string                 `protobuf:"bytes,6,opt,name=current_mission,json=currentMission,proto3" json:"current_mission,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GameplayData) Reset() {
	*x = GameplayData{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameplayData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameplayData) ProtoMessage() {}

func (x *GameplayData) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameplayData.ProtoReflect.Descriptor instead.
func (*GameplayData) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *GameplayData) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *GameplayData) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *GameplayData) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *GameplayData) GetActiveWeapon() string {
	if x != nil {
		return x.ActiveWeapon
	}
	return ""
}

func (x *GameplayData) GetAttackerId() string {
	if x != nil {
		return x.AttackerId
	}
	return ""
}

func (x *GameplayData) GetCurrentMission() string {
	if x != nil {
		return x.CurrentMission
	}
	return ""
}

type CreateGameplayTelemetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data          *GameplayData          `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameplayTelemetryRequest) Reset() {
	*x = CreateGameplayTelemetryRequest{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameplayTelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameplayTelemetryRequest) ProtoMessage() {}

func (x *CreateGameplayTelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameplayTelemetryRequest.ProtoReflect.Descriptor instead.
func (*CreateGameplayTelemetryRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *CreateGameplayTelemetryRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CreateGameplayTelemetryRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CreateGameplayTelemetryRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *CreateGameplayTelemetryRequest) GetData() *GameplayData {
	if x != nil {
		return x.Data
	}
	return nil
}

type PerformanceMetrics struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FpsAvg         float64                `protobuf:"fixed64,1,opt,name=fps_avg,json=fpsAvg,proto3" json:"fps_avg,omitempty"`
	FpsMin         float64                `protobuf:"fixed64,2,opt,name=fps_min,json=fpsMin,proto3" json:"fps_min,omitempty"`
	MemoryUsageMb  int64                  `protobuf:"varint,3,opt,name=memory_usage_mb,json=memoryUsageMb,proto3" json:"memory_usage_mb,omitempty"`
	PingMs         int64                  `protobuf:"varint,4,opt,name=ping_ms,json=pingMs,proto3" json:"ping_ms,omitempty"`
	GpuLoadPercent int64                  `protobuf:"varint,5,opt,name=gpu_load_percent,json=gpuLoadPercent,proto3" json:"gpu_load_percent,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PerformanceMetrics) Reset() {
	*x = PerformanceMetrics{}
	mi := &file_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformanceMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformanceMetrics) ProtoMessage() {}

func (x *PerformanceMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformanceMetrics.ProtoReflect.Descriptor instead.
func (*PerformanceMetrics) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7}
}

func (x *PerformanceMetrics) GetFpsAvg() float64 {
	if x != nil {
		return x.FpsAvg
	}
	return 0
}

func (x *PerformanceMetrics) GetFpsMin() float64 {
	if x != nil {
		return x.FpsMin
	}
	return 0
}

func (x *PerformanceMetrics) GetMemoryUsageMb() int64 {
	if x != nil {
		return x.MemoryUsageMb
	}
	return 0
}

func (x *PerformanceMetrics) GetPingMs() int64 {
	if x != nil {
		return x.PingMs
	}
	return 0
}

func (x *PerformanceMetrics) GetGpuLoadPercent() int64 {
	if x != nil {
		return x.GpuLoadPercent
	}
	return 0
}

type HardwareInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           string                 `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Gpu           string                 `protobuf:"bytes,2,opt,name=gpu,proto3" json:"gpu,omitempty"`
	DriverVersion string                 `protobuf:"bytes,3,opt,name=driver_version,json=driverVersion,proto3" json:"driver_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HardwareInfo) Reset() {
	*x = HardwareInfo{}
	mi := &file_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardwareInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareInfo) ProtoMessage() {}

func (x *HardwareInfo) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardwareInfo.ProtoReflect.Descriptor instead.
func (*HardwareInfo) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{8}
}

func (x *HardwareInfo) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *HardwareInfo) GetGpu() string {
	if x != nil {
		return x.Gpu
	}
	return ""
}

func (x *HardwareInfo) GetDriverVersion() string {
	if x != nil {
		return x.DriverVersion
	}
	return ""
}

type CreatePerformanceTelemetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metrics       *PerformanceMetrics    `protobuf:"bytes,4,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Hardware      *HardwareInfo          `protobuf:"bytes,5,opt,name=hardware,proto3" json:"hardware,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePerformanceTelemetryRequest) Reset() {
	*x = CreatePerformanceTelemetryRequest{}
	mi := &file_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePerformanceTelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePerformanceTelemetryRequest) ProtoMessage() {}

func (x *CreatePerformanceTelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePerformanceTelemetryRequest.ProtoReflect.Descriptor instead.
func (*CreatePerformanceTelemetryRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{9}
}

func (x *CreatePerformanceTelemetryRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CreatePerformanceTelemetryRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CreatePerformanceTelemetryRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *CreatePerformanceTelemetryRequest) GetMetrics() *PerformanceMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *CreatePerformanceTelemetryRequest) GetHardware() *HardwareInfo {
	if x != nil {
		return x.Hardware
	}
	return nil
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\aservice\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x10permission.proto\"\x19\n" +
	"\x17CreateTelemetryResponse\"\x7f\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acountry\x18\x02 \x01(\tR\acountry\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12-\n" +
	"\x12acquisition_source\x18\x04 \x01(\tR\x11acquisitionSource\"\x85\x01\n" +
	"\x13UserBehaviorContext\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x120\n" +
	"\x14total_playtime_hours\x18\x02 \x01(\x01R\x12totalPlaytimeHours\x12\x1d\n" +
	"\n" +
	"last_login\x18\x03 \x01(\tR\tlastLogin\"\xd6\x01\n" +
	"\"CreateUserBehaviorTelemetryRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\x12%\n" +
	"\x04user\x18\x04 \x01(\v2\x11.service.UserInfoR\x04user\x126\n" +
	"\acontext\x18\x05 \x01(\v2\x1c.service.UserBehaviorContextR\acontext\"4\n" +
	"\bLocation\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x01R\x01z\"\xd9\x01\n" +
	"\fGameplayData\x12-\n" +
	"\blocation\x18\x01 \x01(\v2\x11.service.LocationR\blocation\x12\x15\n" +
	"\x06map_id\x18\x02 \x01(\tR\x05mapId\x12\x14\n" +
	"\x05cause\x18\x03 \x01(\tR\x05cause\x12#\n" +
	"\ractive_weapon\x18\x04 \x01(\tR\factiveWeapon\x12\x1f\n" +
	"\vattacker_id\x18\x05 \x01(\tR\n" +
	"attackerId\x12'\n" +
	"\x0fcurrent_mission\x18\x06 \x01(\tR\x0ecurrentMission\"\x9e\x01\n" +
	"\x1eCreateGameplayTelemetryRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\x12)\n" +
	"\x04data\x18\x04 \x01(\v2\x15.service.GameplayDataR\x04data\"\xb1\x01\n" +
	"\x12PerformanceMetrics\x12\x17\n" +
	"\afps_avg\x18\x01 \x01(\x01R\x06fpsAvg\x12\x17\n" +
	"\afps_min\x18\x02 \x01(\x01R\x06fpsMin\x12&\n" +
	"\x0fmemory_usage_mb\x18\x03 \x01(\x03R\rmemoryUsageMb\x12\x17\n" +
	"\aping_ms\x18\x04 \x01(\x03R\x06pingMs\x12(\n" +
	"\x10gpu_load_percent\x18\x05 \x01(\x03R\x0egpuLoadPercent\"Y\n" +
	"\fHardwareInfo\x12\x10\n" +
	"\x03cpu\x18\x01 \x01(\tR\x03cpu\x12\x10\n" +
	"\x03gpu\x18\x02 \x01(\tR\x03gpu\x12%\n" +
	"\x0edriver_version\x18\x03 \x01(\tR\rdriverVersion\"\xe0\x01\n" +
	"!CreatePerformanceTelemetryRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\x125\n" +
	"\ametrics\x18\x04 \x01(\v2\x1b.service.PerformanceMetricsR\ametrics\x121\n" +
	"\bhardware\x18\x05 \x01(\v2\x15.service.HardwareInfoR\bhardware2\x85\a\n" +
	"\aService\x12\xb1\x02\n" +
	"\x1bCreateUserBehaviorTelemetry\x12+.service.CreateUserBehaviorTelemetryRequest\x1a .service.CreateTelemetryResponse\"\xc2\x01\x92A\x98\x01\x12\x1eRecord user behavior telemetry\x1ahReceive and store user behavior events such as session start/end, feature usage, and navigation patternsb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/telemetry/user-behavior\x12\x94\x02\n" +
	"\x17CreateGameplayTelemetry\x12'.service.CreateGameplayTelemetryRequest\x1a .service.CreateTelemetryResponse\"\xad\x01\x92A\x88\x01\x12\x19Record gameplay telemetry\x1a]Receive and store in-game events such as player deaths, level completions, and combat actionsb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/telemetry/gameplay\x12\xae\x02\n" +
	"\x1aCreatePerformanceTelemetry\x12*.service.CreatePerformanceTelemetryRequest\x1a .service.CreateTelemetryResponse\"\xc1\x01\x92A\x99\x01\x12&Record technical performance telemetry\x1aaReceive and store performance snapshots such as FPS, memory usage, ping, and hardware informationb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/telemetry/performanceB\xc6\x02\x92A\xce\x01\x12\x9e\x01\n" +
	"\x1cGame Telemetry Collector API\x12yTelemetry collection service for AccelByte AGS games. Supports user behavior, gameplay, and technical performance events.2\x032.0\"\n" +
	"/telemetryZ\x1f\n" +
	"\x1d\n" +
	"\x06Bearer\x12\x13\b\x02\x1a\rAuthorization \x02\n" +
	"%net.accelbyte.extend.serviceextensionP\x01Z%accelbyte.net/extend/serviceextension\xaa\x02!AccelByte.Extend.ServiceExtensionb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_service_proto_goTypes = []any{
	(*CreateTelemetryResponse)(nil),            // 0: service.CreateTelemetryResponse
	(*UserInfo)(nil),                           // 1: service.UserInfo
	(*UserBehaviorContext)(nil),                // 2: service.UserBehaviorContext
	(*CreateUserBehaviorTelemetryRequest)(nil), // 3: service.CreateUserBehaviorTelemetryRequest
	(*Location)(nil),                           // 4: service.Location
	(*GameplayData)(nil),                       // 5: service.GameplayData
	(*CreateGameplayTelemetryRequest)(nil),     // 6: service.CreateGameplayTelemetryRequest
	(*PerformanceMetrics)(nil),                 // 7: service.PerformanceMetrics
	(*HardwareInfo)(nil),                       // 8: service.HardwareInfo
	(*CreatePerformanceTelemetryRequest)(nil),  // 9: service.CreatePerformanceTelemetryRequest
}
var file_service_proto_depIdxs = []int32{
	1, // 0: service.CreateUserBehaviorTelemetryRequest.user:type_name -> service.UserInfo
	2, // 1: service.CreateUserBehaviorTelemetryRequest.context:type_name -> service.UserBehaviorContext
	4, // 2: service.GameplayData.location:type_name -> service.Location
	5, // 3: service.CreateGameplayTelemetryRequest.data:type_name -> service.GameplayData
	7, // 4: service.CreatePerformanceTelemetryRequest.metrics:type_name -> service.PerformanceMetrics
	8, // 5: service.CreatePerformanceTelemetryRequest.hardware:type_name -> service.HardwareInfo
	3, // 6: service.Service.CreateUserBehaviorTelemetry:input_type -> service.CreateUserBehaviorTelemetryRequest
	6, // 7: service.Service.CreateGameplayTelemetry:input_type -> service.CreateGameplayTelemetryRequest
	9, // 8: service.Service.CreatePerformanceTelemetry:input_type -> service.CreatePerformanceTelemetryRequest
	0, // 9: service.Service.CreateUserBehaviorTelemetry:output_type -> service.CreateTelemetryResponse
	0, // 10: service.Service.CreateGameplayTelemetry:output_type -> service.CreateTelemetryResponse
	0, // 11: service.Service.CreatePerformanceTelemetry:output_type -> service.CreateTelemetryResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_permission_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
